const currencySymbols: Record<string, string> = {
  USD: '$',
  EUR: '€',
  GBP: '£',
  JPY: '¥',
  CNY: '¥',
  INR: '₹',
  KRW: '₩',
  RUB: '₽',
  TRY: '₺',
  UAH: '₴',
  THB: '฿',
  VND: '₫',
  PHP: '₱',
  PLN: 'zł',
  CZK: 'Kč',
  HUF: 'Ft',
  SEK: 'kr',
  NOK: 'kr',
  DKK: 'kr',
  ISK: 'kr',
  CHF: 'CHF',
  CAD: 'C$',
  AUD: 'A$',
  NZD: 'NZ$',
  SGD: 'S$',
  HKD: 'HK$',
  TWD: 'NT$',
  BRL: 'R$',
  MXN: '$',
  ARS: '$',
  CLP: '$',
  COP: '$',
  ZAR: 'R',
  AED: 'د.إ',
  SAR: '﷼',
  ILS: '₪',
  MYR: 'RM',
  IDR: 'Rp',
};

export function getCurrencySymbol(currencyCode: string): string {
  return currencySymbols[currencyCode?.toUpperCase()] ?? currencyCode;
}
